[package]
name = "pokemon_sprite"
version = "0.1.0"
authors = ["Franco Colmenarez <info@francoacg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
